version: "3"

services:
  rng:
    build: rng
    ports:
      - "8001:80"
    container_name: rng
    networks:
      - Mainsv

  hasher:
    build: hasher
    ports:
      - "8002:80"
    container_name: hasher
    networks:
      - Mainsv

  webui:
    build: webui
    ports:
      - "8000:80"
    volumes:
      - "./webui/files/:/files/"
    container_name: webui
    networks:
      - Mainsv

  redis:
    image: redis
    container_name: redis
    networks:
      - Mainsv

  worker:
    build: worker
    networks:
      - Mainsv

networks:
  Mainsv:
    external: true
